name: video_player
description: Flutter plugin for displaying inline video with other Flutter
  widgets on Android, iOS, and web.
repository: https://github.com/flutter/plugins/tree/master/packages/video_player/video_player
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+video_player%22
version: 2.2.7
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.videoplayer
        pluginClass: VideoPlayerPlugin
      ios:
        pluginClass: FLTVideoPlayerPlugin
      web:
        default_package: video_player_web

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.3.0

  video_player_platform_interface:
    git:
      url: git@github.com:d3xt3r2909/plugins.git
      path: packages/video_player/video_player_platform_interface
      ref: v2.2.7-ads.dev2

  video_player_web:
    git:
      url: git@github.com:d3xt3r2909/plugins.git
      path: packages/video_player/video_player_web
      ref: v2.2.7-ads.dev2

  html: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.10.0
  pigeon: ^0.1.21

